### ISSUE TITLE
Scan All Versions

### ISSUE THREAD

**Issue by weiqingy** [hortonworks-spark/shc#101]
Can not get all versions of all row keys stored in a table: https://community.hortonworks.com/questions/83870/spark-hbase-connector-how-to-getscan-all-versions.html

**Comment by explicite** [comment]
We have same problem. We are using `HBaseRelation.MIN_STAMP` nad `HBaseRelation.MAX_STAMP` in DataFrameReader options and cant get other version. Always last. 
We are using:
```
Spark 1.6.3
shc-core 1.0.1-1.6-s_2.10
Scala 2.10.4
HDP Sandbox 2.6.1.0
HBase 1.1.2
```
If you need more information I will gladly share them.
Thanks

**Comment by weiqingy** [comment]
The PR https://github.com/hortonworks-spark/shc/pull/193 is for this issue.

**Comment by weiqingy** [comment]
PR https://github.com/hortonworks-spark/shc/pull/193 has been merged. Close this.
