### ISSUE TITLE
Can not create a Table in a given namespace using Apache HBase 1.2.0

### ISSUE THREAD

**Issue by adamdec** [hortonworks-spark/shc#103]
Hi, recently I have switched an HBase version from
`<hbase.version>1.1.2</hbase.version>`
to
`<hbase.version>1.2.0</hbase.version>`
as this is the official version in the recent Cloudera 5.10.0 distribution.

After the switch, shc is not able to create an HBase table in a given namespace (not "default" one). I went briefly throught the code and found the solution. To have it working some small fixes needs to be made:

**File: HBaseRelation.scala**
line 152, replace
`val r = connection.getRegionLocator(TableName.valueOf(catalog.name)).getAllRegionLocations`
with
val r = connection.getRegionLocator(tName).getAllRegionLocations

line 171, replace
`hbaseConf.set(TableOutputFormat.OUTPUT_TABLE, catalog.name)`
with
`hbaseConf.set(TableOutputFormat.OUTPUT_TABLE, s"${catalog.namespace}:${catalog.name}")`

**File: RegionResource.scala**
line 94, replace
`rl = connection.getRegionLocator(TableName.valueOf(relation.catalog.name))`
with
`rl = connection.getRegionLocator(TableName.valueOf(s"${relation.catalog.namespace}:${relation.catalog.name}")`

**File: TableResource.scala**
line 126, replace
`table = connection.getTable(TableName.valueOf(relation.catalog.name))`
with
`table = connection.getTable(TableName.valueOf(s"${relation.catalog.namespace}:${relation.catalog.name}"))`

I can create a PR for it.

**Comment by weiqingy** [comment]
Thanks, @adamdec . From your solution here, I can see the problem in the current code. Have you tested the solution with hbase.version 1.1.2? If all the testing passed, yes, please make a PR.

**Comment by weiqingy** [comment]
Hi, @adamdec Is it any update for this issue? Thanks.

**Comment by adamdec** [comment]
It is on my TODO list :)

**Comment by rayokota** [comment]
I ran into this issue as well, so created PR#114

**Comment by weiqingy** [comment]
PR#114 has been merged. Thanks.

**Comment by weiqingy** [comment]
This has been resolved. Let's close this. Thanks.
