### ISSUE TITLE
Not able to use catalog with pipe delimited composite key

### ISSUE THREAD

**Issue by tenstriker** [hortonworks-spark/shc#104]
This might be related to https://github.com/hortonworks-spark/shc/issues/72
We have a composite key in a form of "key1|key2|key3|key4|key5|key6|key7|key8|key9" . 
e.g.
`000028|201001|401|302|501|9007|805|1999|272505055   column=cf:amount, timestamp=1489435148627, value=149441`

Following is snippet of catalog.

`def busCatalogComposite = StringContext.treatEscapes("""{
              |"table":{"name": "$mytablename" },
              |"rowkey":"key1|key2|key3|key4|key5|key6|key7|key8|key9",
              |"columns":{
                |"id":{"cf":"rowkey", "col":"key1", "type":"string"},
                |"period":{"cf":"rowkey", "col":"key2", "type":"string"},`

Getting following error upon call to withCatalog method to load hbase table:

`  def withCatalog(cat: String) = {
    sparkSession
    .read
    .options(Map(HBaseTableCatalog.tableCatalog -> cat))
    .format("org.apache.spark.sql.execution.datasources.hbase")
    .load
  }`

Caused by: java.lang.UnsupportedOperationException: empty.tail
	at scala.collection.TraversableLike$class.tail(TraversableLike.scala:421) ~[scala-library-2.11.8.jar!/:na]
	at scala.collection.mutable.ArraySeq.scala$collection$IndexedSeqOptimized$$super$tail(ArraySeq.scala:46) ~[scala-library-2.11.8.jar!/:na]
	at scala.collection.IndexedSeqOptimized$class.tail(IndexedSeqOptimized.scala:129) ~[scala-library-2.11.8.jar!/:na]
	at scala.collection.mutable.ArraySeq.tail(ArraySeq.scala:46) ~[scala-library-2.11.8.jar!/:na]
	at org.apache.spark.sql.execution.datasources.hbase.HBaseTableCatalog.initRowKey(HBaseTableCatalog.scala:140) ~[shc-1.0.1-1.6-s_2.11-SNAPSHOT.jar!/:1.0.0-2.0-s_2.11]
	at org.apache.spark.sql.execution.datasources.hbase.HBaseTableCatalog.<init>(HBaseTableCatalog.scala:151) ~[shc-1.0.1-1.6-s_2.11-SNAPSHOT.jar!/:1.0.0-2.0-s_2.11]
	at org.apache.spark.sql.execution.datasources.hbase.HBaseTableCatalog$.apply(HBaseTableCatalog.scala:208) ~[shc-1.0.1-1.6-s_2.11-SNAPSHOT.jar!/:1.0.0-2.0-s_2.11]
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.<init>(HBaseRelation.scala:162) ~[shc-1.0.1-1.6-s_2.11-SNAPSHOT.jar!/:1.0.0-2.0-s_2.11]
	at org.apache.spark.sql.execution.datasources.hbase.DefaultSource.createRelation(HBaseRelation.scala:49) ~[shc-1.0.1-1.6-s_2.11-SNAPSHOT.jar!/:1.0.0-2.0-s_2.11]
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:330) ~[spark-sql_2.11-2.0.1-mapr-1611.jar!/:2.0.1-mapr-1611]
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:149) ~[spark-sql_2.11-2.0.1-mapr-1611.jar!/:2.0.1-mapr-1611]
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:122) ~[spark-sql_2.11-2.0.1-mapr-1611.jar!/:2.0.1-mapr-1611]

**Comment by weiqingy** [comment]
From the error stack, it seems you were using [v1.0.1-1.6](https://github.com/hortonworks-spark/shc/tree/v1.0.1-1.6). For the releases before [v1.1.0-1.6 ](https://github.com/hortonworks-spark/shc/tree/v1.0.1-1.6)(for spark 1.6.x) and [v1.1.0-2.0 ](https://github.com/hortonworks-spark/shc/tree/v1.1.0-2.0) / [v1.1.0-2.1](https://github.com/hortonworks-spark/shc/tree/v1.1.0-2.1)(for spark 2.x), for use cases of composite keys, you may want to refer [CompositeKey example](https://github.com/hortonworks-spark/shc/blob/v1.0.1-1.6/examples/src/main/scala/org/apache/spark/sql/execution/datasources/hbase/CompositeKey.scala#L60). Take `"rowkey":"key1|key2|key3" ` as an example. In catalog definition, `"rowkey":"key1|key2|key3"` should be "rowkey":"key1:key2:key3". Also, except for the last dimension of the composite key `key3`, you need to specify the length of key1 and Key2 if the length of their data type is variable (like string and byte array). In the releases `v1.1.0-x.x`, we have added Phoenix coder to remove the limitation, you donot need to specify the `length` of each individual key of composite keys any more, but you need to specify the value of table coder as Phoenix, please refer [DataCoder example](https://github.com/hortonworks-spark/shc/blob/v1.1.0-1.6/examples/src/main/scala/org/apache/spark/sql/execution/datasources/hbase/DataCoder.scala#L57).

**Comment by tenstriker** [comment]
Yes I am using v1.0.1-1.6 . I will try out v1.1.0-2.0 since I'm also using spark 2.x. Thanks. Let me ask another question on query performance of using composite key catalogue vs regular. I see two path

1) Use non composite key ; Convert DataFrame into DataSet of Case class where all dimensions are fields. Later I can do Filter based on those fields (dimensions) . would this even work as shc knows nothing about those fields individually.

2) Use composite key; so each dimension has schema now and I can either query on them directly via dataframe or dataset. 

Would there be any performance advantage of one over another?

**Comment by weiqingy** [comment]
I do not understand your question. For "`1. Use non composite key ;`", if all the data have been read inside a DataFrame, you do can convert into a DataSet, and do whatever you want, all of these queries will be done by Spark, that has nothing to do with SHC.

**Comment by weiqingy** [comment]
If you are mention this scenario: DataFrame -> DataSet -> save the data into HBase with SHC -> do some queries with SHC like some filtering, then the first thing is you need to define your catalog to tell SHC how to save the data in HBase. After that, if you do the queries with SHC, and SHC know nothing about the data (like just know there is some byte array), then SHC will read all data from HBase into Spark without any optimizations like `filters push down', and let Spark do all queries on all the data.

**Comment by tenstriker** [comment]
I updated my previous comment. In both cases DataFrame is created by defining catalog and using HBaseTableCatalog.tableCatalog (withCatalog method of your example). But in first case rowkey is one dimension while in second its a composite key with multiple dimensions.

**Comment by tenstriker** [comment]
Getting "java.lang.ClassNotFoundException: org.apache.phoenix.schema.types.PDataType" when using Phoenix as a tableCoder

**Comment by weiqingy** [comment]
@tenstriker Currently, for composite keys, SHC only does 'filter push down' for the first dimension of the composite key, so if you have the choice, `non composite key` is recommended, but we'll improve the performance of composite keys later.

**Comment by weiqingy** [comment]
`1. Use non composite key in catalogue definition; Create DataFrame using HBaseTableCatalog.tableCatalog; Convert DataFrame into DataSet of Case class where all dimensions are fields. Later I can do Filter based on those fields (dimensions) . would this even work as shc knows nothing about those fields individually.`

Answer: yes, it works. After data have been read into DataFrame, the `Filter` will be done by Spark. SHC does not need to know anything about the DataSet.

**Comment by tenstriker** [comment]
@weiqingy thanks for clarification on key usage. I want to do predicate pushdown as much as possible as that's the main use case for us.
What all hbase filters are supported by shc? Does it also support prefixfilter, columnvaluefilter?

**Comment by weiqingy** [comment]
Filters supported by SHC are [here](https://github.com/hortonworks-spark/shc/blob/master/core/src/main/scala/org/apache/spark/sql/execution/datasources/hbase/HBaseFilter.scala#L162), where SHC converts filters supported by Spark to HBase standard filters.

**Comment by tenstriker** [comment]
Thanks!
