### ISSUE TITLE
incremental loading

### ISSUE THREAD

**Issue by nuoluo** [hortonworks-spark/shc#108]
I have hbase table that increase continuously, and the spark job only need the new data everyday using this code:

`val df = withCatalog(catalog)`
`val s = df.filter((($"col0" >= day+"00:00:00" && $"col0" < day+"23:59:59")`

Does the shc load the whole table before filtering?
If it does, is there a way load the table in batch and stop it as soon as the newly loaded data doesn't match the filter?

**Comment by weiqingy** [comment]
SHC will not load the whole table for `">="` and `"<"`, the filters will be pushed down to HBase. Only the data which are in the range of `($"col0" >= day+"00:00:00" && $"col0" < day+"23:59:59")` will go back to Spark.

**Comment by nuoluo** [comment]
Thanks for replying. That seems great, but i do notice it takes longer and longer to load the new data as the table grows. Is it because hbase scans through the whole table every time I read? Can specify the row-id or something else to tell hbase which portion of the table to read? Thanks

**Comment by jerryjch** [comment]
When you specify a query the way you had, HBase has to scan all the rows to compare the column values and filter them.  If you have a properly designed rowkey, you can specify predicates on the rowkey to if you get better response time.

**Comment by chetkhatri** [comment]
@nuoluo if you satisfied with answer could you close this issue.
