### ISSUE TITLE
Custom serdes are not working

### ISSUE THREAD

**Issue by rayokota** [hortonworks-spark/shc#117]
Hi,

I have created a custom serde to work against a graph stored in HBase (using [HGraphDB](https://github.com/rayokota/hgraphdb)) so that I could integrate SHC with [Spark GraphFrames](https://graphframes.github.io).  I wrote a blog about it [here](https://yokota.blog/2017/04/02/graph-analytics-on-hbase-with-hgraphdb-and-spark-graphframes/).  I ran into a couple of issues for which I have filed pull requests (#113, #114, #116).  

Other than those minor issues, the integration of SHC with GraphFrames worked very well.

Thanks!

**Comment by weiqingy** [comment]
Hi, @rayokota. Thank you very much for help improving SHC. Great PRs. I've merged them.

Could you please also update your blog so people know about this and the issues are gone? Thanks again.

**Comment by rayokota** [comment]
Thanks @weiqingy !  I've updated the blog to say the issues have been merged.  Thanks for your quick response!
