### ISSUE TITLE
HBaseTableCatalog.initRowKey issue when inserting into HBase

### ISSUE THREAD

**Issue by ymahajan** [hortonworks-spark/shc#128]
`Exception in thread "main" java.lang.UnsupportedOperationException: empty.tail
	at scala.collection.TraversableLike$class.tail(TraversableLike.scala:421)
	at scala.collection.mutable.ArraySeq.scala$collection$IndexedSeqOptimized$$super$tail(ArraySeq.scala:46)
	at scala.collection.IndexedSeqOptimized$class.tail(IndexedSeqOptimized.scala:129)
	at scala.collection.mutable.ArraySeq.tail(ArraySeq.scala:46)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseTableCatalog.initRowKey(HBaseTableCatalog.scala:185)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseTableCatalog.<init>(HBaseTableCatalog.scala:199)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseTableCatalog$.apply(HBaseTableCatalog.scala:293)
	at org.apache.spark.sql.execution.datasources.hbase.HBaseRelation.<init>(HBaseRelation.scala:80)
	at org.apache.spark.sql.execution.datasources.hbase.DefaultSource.createRelation(HBaseRelation.scala:59)
	at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:429)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:211)	
`

**Comment by ymahajan** [comment]
Here is my catalog - 
` def airlineCatalog = s"""{
                   |"table":{"namespace":"default", "name":"airline"},
                   |"rowkey":"AIRTIME",
                   |"columns":{
                   |"YEAR_":{"cf":"cf1", "col":"YEAR_", "type":"int"},
                   |"MONTH":{"cf":"cf2", "col":"MONTH", "type":"int"},
                   |"DAYOFMONTH":{"cf":"cf3", "col":"DAYOFMONTH", "type":"int"},
                   |"DAYOFWEEK":{"cf":"cf4", "col":"DAYOFWEEK", "type":"int"},
                   |"DEPTIME":{"cf":"cf5", "col":"DEPTIME", "type":"int"},
                   |"CRSDEPTIME":{"cf":"cf6", "col":"CRSDEPTIME", "type":"int"},
                   |"ARRTIME":{"cf":"rowkey", "col":"ARRTIME", "type":"int"},
                   |"CRSARRTIME":{"cf":"cf8", "col":"CRSARRTIME", "type":"int"},
                   |"UNIQUECARRIER":{"cf":"cf9", "col":"UNIQUECARRIER", "type":"string"},
                   |"FLIGHTNUM":{"cf":"cf10", "col":"FLIGHTNUM", "type":"int"},
                   |"TAILNUM":{"cf":"cf11", "col":"TAILNUM", "type":"string"},
                   |"ACTUALELAPSEDTIME":{"cf":"cf12", "col":"ACTUALELAPSEDTIME", "type":"int"},
                   |"CRSELAPSEDTIME":{"cf":"cf13", "col":"CRSELAPSEDTIME", "type":"int"},
                   |"AIRTIME":{"cf":"cf14", "col":"AIRTIME", "type":"int"},
                   |"ARRDELAY":{"cf":"cf15", "col":"ARRDELAY", "type":"int"},
                   |"DEPDELAY":{"cf":"cf16", "col":"DEPDELAY", "type":"int"},
                   |"ORIGIN":{"cf":"cf17", "col":"ORIGIN", "type":"string"},
                   |"DEST":{"cf":"cf18", "col":"DEST", "type":"string"},
                   |"DISTANCE":{"cf":"cf19", "col":"DISTANCE", "type":"int"},
                   |"TAXIIN":{"cf":"cf20", "col":"TAXIIN", "type":"int"},
                   |"TAXIOUT":{"cf":"cf21", "col":"TAXIOUT", "type":"int"},
                   |"CANCELLED":{"cf":"cf22", "col":"CANCELLED", "type":"int"},
                   |"CANCELLATIONCODE":{"cf":"cf23", "col":"CANCELLATIONCODE", "type":"string"},
                   |"DIVERTED":{"cf":"cf24", "col":"DIVERTED", "type":"int"},
                   |"CARRIERDELAY":{"cf":"cf25", "col":"CARRIERDELAY", "type":"int"},
                   |"WEATHERDELAY":{"cf":"cf26", "col":"WEATHERDELAY", "type":"int"},
                   |"NASDELAY":{"cf":"cf27", "col":"NASDELAY", "type":"int"},
                   |"SECURITYDELAY":{"cf":"cf28", "col":"SECURITYDELAY", "type":"int"},
                   |"LATEAIRCRAFTDELAY":{"cf":"cf29", "col":"LATEAIRCRAFTDELAY", "type":"int"},
                   |"ARRDELAYSLOT":{"cf":"cf30", "col":"ARRDELAYSLOT", "type":"int"}
                   |}
                   |}""".stripMargin`

**Comment by weiqingy** [comment]
Could you change the value of `cf` in `|"AIRTIME":{"cf":"cf14", "col":"AIRTIME", "type":"int"}` in your catalog definition from `cf14` to `rowkey` and rerun it again?

**Comment by weiqingy** [comment]
You can refer [here](https://github.com/hortonworks-spark/shc/blob/master/examples/src/main/scala/org/apache/spark/sql/execution/datasources/hbase/HBaseSource.scala#L55) to define your catalog.

**Comment by ymahajan** [comment]
@weiqingy Thanks. It works fine now.
