### ISSUE TITLE
How to add resource to HBaseConfiguration

### ISSUE THREAD

**Issue by wuminorb** [hortonworks-spark/shc#160]
Hi:
  We have some extra file want to add to HBaseConfiguration. 
  It also be done with:
``` java
hbaseConfiguration.addResource(externalConfigFileURL);
```
  
  How to do it when useing shc? Is there a solution or walk-around?

**Comment by weiqingy** [comment]
There are two ways to do this:
(1) put your extra configurations in a file, and make the file as the value of `HBaseRelation.HBASE_CONFIGFILE`. Refer to [here](https://github.com/hortonworks-spark/shc/blob/master/examples/src/main/scala/org/apache/spark/sql/execution/datasources/hbase/LRJobAccessing2Clusters.scala#L107).

(2) put your extra configurations in json format, and make the json as the value of `HBaseRelation.HBASE_CONFIGURATION`. 
```
sqlContext
  .read
  .options(Map(HBaseTableCatalog.tableCatalog->cat, HBaseRelation.HBASE_CONFIGURATION -> yourjson))
  .format("org.apache.spark.sql.execution.datasources.hbase")
  .load()
```
