### ISSUE TITLE
How to apply TimeRange Filter in SHC

### ISSUE THREAD

**Issue by AtulKumVerma** [hortonworks-spark/shc#184]
> @weiqingy How to apply TimeRange Filter, Rowkey filter and different kind of filters on hbase at the time of data scaning in catalog by using Spark Hbase Connector(SHC).

**Comment by weiqingy** [comment]
@AtulKumVerma You may want to check the tests cases like [here](https://github.com/hortonworks-spark/shc/blob/master/core/src/test/scala/org/apache/spark/sql/DefaultSourceSuite.scala#L269)

**Comment by AtulKumVerma** [comment]
@Weiqing
thanks it works !!!

---
*Thanks & Regards*

*Er. Atul VermaStudent of CSE department.*
