### ISSUE TITLE
can i fetch data of particular rowKey from hbase 

### ISSUE THREAD

**Issue by AtulKumVerma** [hortonworks-spark/shc#194]
@weiqingy 
can i fetch data of particular rowKey from hbase using SHC without fetching all data of hbase
we can also able to add min and max timestamp but didn't find anything for rowkey.
here some code 

                

> SparkConf sparkConf = new SparkConf();
> sparkConf.setAppName("local");
> sparkConf.setMaster("local");
> 
> SparkSession sparkSession = new SparkSession(new SparkContext(sparkConf));
> SQLContext sqlcontxt = new SQLContext(sparkSession);
> 
> String query = "select * from NVReport";
> Map<String, String> colMap = new HashMap<String, String>();
> String cat = ConfigUtil.getConfigurationValue("emp2");
> colMap.put(HBaseTableCatalog.tableCatalog(), cat);
>Dataset dataset = sqlcontxt.read().options(colMap).format("org.apache.spark.sql.execution.datasources.hbase").load();

i also find something like HBaseTableCatalog.rowKey() but its not working
 colMap.put(HBaseTableCatalog.rowKey(), "key");

**Comment by weiqingy** [comment]
Hi @AtulKumVerma,

Yes, you can not make `colMap.put(HBaseTableCatalog.rowKey(), "key")`. However, as SHC pushes filters down into Hbase, you may want to do `select` on your dataframe to tell Hbase only return rowKey back to Spark.

val df = dataframe.select("col00") // assume "col00" is mapping to rowKey in your catalog
df.show() // you will see Hbase only return row key

**Comment by AtulKumVerma** [comment]
Appreciate with this but i have another issue.
see lets i have some data in hbase like 
-----------------------------
| rowKey | col1 | col2 |
-----------------------------
|   19      |  x     | A      |
|   23      |  y     | B      |
|   25      |  z     | C      |
-----------------------------

so i want to get that data whose rowkey is 23.
-----------------------------
| rowKey | col1 | col2 |
-----------------------------
|   23      |  y     | B      |
-----------------------------
**Actually i dont know its internall architecture how dataframe actually works if i use like .
val df = select(col("rowkey")).filter(col("rowkey")).equals("23");
so this will fetch all rowkey i.e. 19,23,25 from hbase and than apply filter on rowkey column to find whose value is 23.
OR
this will fetch that rowkey from hbase whose value is 23.**

Thanks in advance.

**Comment by weiqingy** [comment]
@AtulKumVerma  The later one - "fetch that rowkey only from hbase whose value is 23". (of course, you may want to invoke some Spark action operations like show(), count(), etc)

**Comment by AtulKumVerma** [comment]
Thanks @weiqingy .
