### ISSUE TITLE
HDP 2.6.3 Spark 2.2.0

### ISSUE THREAD

**Issue by Neuw84** [hortonworks-spark/shc#201]
Hello, 

It would be possible to upload a version built for Spark 2.2.0 (that is already available on HDP 2.6.3) to the Hortonworks public repo?

If it's not possible any deadline on this matter?

Thanks!

**Comment by weiqingy** [comment]
Hi @Neuw84 We have uploaded a version for Spark 2.2.0, HDP 2.6.3, you may want to use it (http://repo.hortonworks.com/content/repositories/releases/com/hortonworks/shc/shc/)

--packages com.hortonworks.shc:shc-core:1.1.0.2.6.3.0-235
--repositories http://nexus-private.hortonworks.com/nexus/content/groups/public 

```
spark-submit  --class your.application.class --master yarn-cluster --packages com.hortonworks.shc:shc-core:1.1.0.2.6.3.0-235 --num-executors 4 --driver-memory 512m --executor-memory 512m --executor-cores 1 --files /usr/hdp/current/hbase-client/conf/hbase-site.xml --repositories http://nexus-private.hortonworks.com/nexus/content/groups/public /your/application/jar 
```
Lets know if you hit any issues.
We are planning to publish new releases around Jan 2018.

**Comment by weiqingy** [comment]
New version for HDP 2.3.x and HDP 2.4.x http://nexus-private.hortonworks.com/nexus/content/repositories/IN-QA/com/hortonworks/shc/shc/

**Comment by Neuw84** [comment]
Thanks! 
Will test it and let you know if I hit any issues.
