### ISSUE TITLE
NullPointerException from .ZooKeeperWatcher.getMetaReplicaNodes

### ISSUE THREAD

**Issue by gypsysunny** [hortonworks-spark/shc#208]
INFO ZooKeeper: Initiating client connection, connectString=localhost:2181 sessionTimeout=90000 watcher=hconnection-0x3d57fb9e0x0, quorum=localhost:2181, baseZNode=/hbase
18/01/12 15:23:50 INFO ClientCnxn: Opening socket connection to server localhost.localdomain/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
18/01/12 15:23:50 INFO ClientCnxn: Socket connection established to localhost.localdomain/0:0:0:0:0:0:0:1:2181, initiating session
18/01/12 15:23:50 INFO ClientCnxn: Session establishment complete on server localhost.localdomain/0:0:0:0:0:0:0:1:2181, sessionid = 0x35e2998f3c1ed53, negotiated timeout = 40000
18/01/12 15:23:50 INFO ZooKeeperRegistry: ClusterId read in ZooKeeper is null

this is the code snippet where the issue emerged
  sparkSession.read.options(Map(HBaseTableCatalog.tableCatalog -> cat))
        .format("org.apache.spark.sql.execution.datasources.hbase")
        .load()

can anyone give any tips on how i could connect to the correct server rather than localhost? thank you in advance.

**Comment by weiqingy** [comment]
You may want to try: copy hbase-site.xml from /usr/hdp/current/hbase-client/conf/ to /usr/hdp/current/spark-client/conf/.

**Comment by gypsysunny** [comment]
what if i put hbase-site.xml to my project.dir/src/main/resources/? does that make sense?

**Comment by gypsysunny** [comment]
i have tried the way. it works.
