### ISSUE TITLE
how to specify the region in pyspark?

### ISSUE THREAD

**Issue by shen-xianpeng** [hortonworks-spark/shc#218]
org.apache.spark.sql.execution.datasources.hbase.InvalidRegionNumberException: Creating a new table sh
ould specify the number of regions which must be greater than 3.

i saw in issue doing like this:
df.write.options(map(catalog=cat, HBaseTableCatalog.newTable -> "5")).mode("append").format(data_source_format).save()

but how to pass param 'HBaseTableCatalog.newTable'  in pyspark?

**Comment by shen-xianpeng** [comment]
sorry,  i misspelled the table name.

i works now

**Comment by ser0t0nin** [comment]
@shen-xianpeng so how did you passed the newTable parameter in pyspark finally?

**Comment by fouqau4** [comment]
@ser0t0nin 
You can refer to this page for passing the demanded parameters.
https://github.com/apache/hbase/blob/master/hbase-spark/src/main/scala/org/apache/spark/sql/datasources/hbase/HBaseTableCatalog.scala

The corresponding parameter of "newTable" is "newtable".
You can assign the number of regions by adding this line :
df.write.options( catalog = your_catalog, newtable = num_of_regions ).format( your_format  ).save()

Work for me.
