### ISSUE TITLE
java.lang.IllegalArgumentException: Field "col0" does not exist

### ISSUE THREAD

**Issue by gypsysunny** [hortonworks-spark/shc#224]
def voyageCatalog = s"""{
                          |"table":{"namespace":"default", "name":"${voyageTableName}", "tableCoder":"PrimitiveType"},
                          |"rowkey":"key",
                          |"columns":{
                          |"col0":{"cf":"rowkey", "col":"key", "type":"string"},
                          |"y":{"cf":"Y", "col":"y", "type":"string"}
                          |}
                          |}""".stripMargin 
ds.write.mode(SaveMode.Overwrite)
      .options(Map(HBaseTableCatalog.tableCatalog -> cat))
      .format("org.apache.spark.sql.execution.datasources.hbase")
      .save()

could you please give a tip on how to address this issue?thank you in advance.

**Comment by weiqingy** [comment]
Could you check the schema of `ds`? Is "col0" a field of 'ds'?

**Comment by mantovani** [comment]
The _catalog_ fields name **must** match the dataframe name.

`val df = spark.sparkContext.makeRDD(1 to 5).map(i => (i.toString, i.toString)).toDF("col0", "y")`

**Comment by gypsysunny** [comment]
ok, thank you both.
