### ISSUE TITLE
Null column values in dataframe (from hbase table)

### ISSUE THREAD

**Issue by AbdullahServantOfAllah** [hortonworks-spark/shc#226]
have following data in table:
hbase(main):001:0> scan 'stagetable'
ROW                                 COLUMN+CELL                                                                                          
 1                                  column=chks:jobId, timestamp=1521457677132, value=999                                                
 1                                  column=chks:storeId, timestamp=1521457677132, value=888                                              
 abc                                column=chks: storeId, timestamp=1521194663969, value=dsdsdsds                                        
 abc                                column=chks:jobId, timestamp=1521194653828, value=dsdsdsds                                           
 row1                               column=chks: storeId, timestamp=1521181318443, value=456                                             
 row1                               column=chks:jobId, timestamp=1521181272719, value=123                                                
3 row(s) in 0.2310 seconds

when i read in spark via SHC connector I get null values for all columns other than rowkey:
-------+-----+-------+-------------+------+----------+-------------------+----------------------+--------------+------+-------------------+-------+
|checkId|jobId|storeId|
-+------+-------------------+-------+
|      1| null|   null|         
|    abc| null|   null|         
|   row1| null|   null|         
+-------+-----+-------+

code I wrote is as below:
val catalog2 =
    s"""{
       |"table":{"namespace":"default", "name":"stagetable"},
       |"rowkey":"checkId",
       |"columns":{
       |"checkId":{"chks":"rowkey", "col":"checkId", "type":"string"},
       |"jobId":{"chks":"jobId", "col":"jobId", "type":"string"},
       |"storeId":{"chks":"storeId", "col":"storeId", "type":"int"}
       |}
       |}""".stripMargin
  //val sqlContext = new SQLContext(spark)
  def withCatalog(cat: String): DataFrame = {
    spark
      .read
      .options(Map(HBaseTableCatalog.tableCatalog->cat))
      .format("org.apache.spark.sql.execution.datasources.hbase")
    .load()
  }

  val df = withCatalog(catalog2)
  df.printSchema()
  df.show()

**Comment by weiqingy** [comment]
It seems the definition of catalog2 is not correct. Please refer to the [examples](https://github.com/hortonworks-spark/shc/blob/master/examples/src/main/scala/org/apache/spark/sql/execution/datasources/hbase/HBaseSource.scala#L73) for the catalog definition format. `"chks":"rowkey"` should be `"cf":"chks"` ?

**Comment by AbdullahServantOfAllah** [comment]
Thanks after trial and error I got the schema definition right.
