### ISSUE TITLE
Date Type Error

### ISSUE THREAD

**Issue by AbdullahServantOfAllah** [hortonworks-spark/shc#232]
How to use dates in the schema definition. I tried using below:

al catalog =
    s"""{
       |"table":.....
         |"duedate":{"cf":"ns", "col":"dueDate", "type":"date"},

But got below error:
java.lang.UnsupportedOperationException: PrimitiveType coder: unsupported data type 2017-01-18

**Comment by hemangakbari** [comment]
hi @AbdullahServantOfAllah 
Were you able to solve the error?
if yes then could you share the solution.
