### ISSUE TITLE
Cache connections to hbase for long-lived processes

### ISSUE THREAD

**Issue by nickdevp** [hortonworks-spark/shc#24]
The spark-hbase-connector doesn't cache connection objects to hbase. Specifically, the call to 'ConnectionFactory.createConnection' is done each time in HBaseResources.scala. This is an expensive operation as documented at https://hbase.apache.org/apidocs/org/apache/hadoop/hbase/client/Connection.html. For long-lived processes, it would be very useful to keep a connection cache.

**Comment by Sherry302** [comment]
Hi, @nickdevp I have created a PR for this issue. Could you please review it? Thanks. https://github.com/hortonworks-spark/shc/pull/40

**Comment by nickdevp** [comment]
Hi Sherry,
Might be my mistake, but please take a look:
The connection is cached per instance of HBaseConfiguration. It looks like the configuration is created each time a new HBaseRelation is created (see value 'hConf' at line HBaseRelation.scala#L166 and hbaseConf definition at line 176). In test mode, the HBaseConfiguration is static. I am not sure at what frequency Spark creates a new relation, but I'm guessing it is doing it every time through the DefaultSource.createRelation method. This would mean that your fix only works as expected in test mode.

**Comment by nickdevp** [comment]
How do I enable this through the spark data source api (e.g., how do you set 'SparkHBaseConf.enableCache' to true through a data source option?)

**Comment by Sherry302** [comment]
Hi, @nickdevp @shubhamchopra I have updated the PR. With that PR, there is only one Connection object if the HBase cluster is the same. But I want to confirm with you: how long the Connection object should be kept after it is created? the entire life time of Spark applications? or when 2-3 hours after it created, if no one is using it, it should be closed? I am not sure what is the best practice for the user.

**Comment by weiqingy** [comment]
Hi, @nickdevp @shubhamchopra The PR #45 is the second version of connection sharing implementation, which adds a background thread to close the idle connections. Please feel free to add any comments. Thanks.
