### ISSUE TITLE
Multiple copies of binary data during Result -> Row conversion

### ISSUE THREAD

**Issue by nickdevp** [hortonworks-spark/shc#25]
Please look at:
https://github.com/hortonworks-spark/shc/blob/master/src/main/scala/org/apache/spark/sql/execution/datasources/hbase/HBaseTableScan.scala#L115
and
https://github.com/hortonworks-spark/shc/blob/master/src/main/scala/org/apache/spark/sql/execution/datasources/hbase/Utils.scala#L58

CellUtil.clone will already create a copy of the data. Another copy is being made within Utils.scala. Generally, binary data (blobs) can be fairly large, so copying may be an expensive operation.

**Comment by Sherry302** [comment]
Hi, @nickdevp I can not open the above links. Is there anything I need to pay attention to? Thanks.

**Comment by nickdevp** [comment]
Updated the links
The files are this repository:
HBaseTableScan.scala (line 115) and Utils.scala (line 58)

**Comment by Sherry302** [comment]
Thanks @nickdevp for this. It has been resolved, so close it.

**Comment by Sherry302** [comment]
Hi, @nickdevp Could you close this issue? Thanks.
