### ISSUE TITLE
Filtering data based on rowkey

### ISSUE THREAD

**Issue by libsgh** [hortonworks-spark/shc#250]
Hi @weiqingy 
Does the rowkey filter field be filtered through startRow, endRow? If the amount of data is large, there will be no performance problems. In my business scenario, a day's data is synchronized to hive, and rowkey is designed as a timestamp suffix, such as "xxxx_20180501".

Code:
```
 df.filter($"col0" === "xxxx_20180501" || $"col0" <= "xxxx_20180501").select("id","col0").show()
```
Thanks a lot.

**Comment by msdevanms** [comment]
Any update on this query ?

**Comment by sachinjain024** [comment]
@libsgh It looks like less than (or less than equal to) filter is supported. Have a look at this: https://github.com/hortonworks-spark/shc/blob/master/core/src/main/scala/org/apache/spark/sql/execution/datasources/hbase/HBaseFilter.scala#L209

Basically, these filters are converted to Hbase filters and pushed while reading the data. Not sure if triple equals is supported. You may want to try double equals as well in your first condition.

Is it not working for you ?

More Information on HBase Filters -
1. https://hbase.apache.org/book.html#client.filter
2. https://stackoverflow.com/questions/7256100/scan-with-filter-using-hbase-shell
