### ISSUE TITLE
NoSuchColumnFamilyException

### ISSUE THREAD

**Issue by GawkVictor** [hortonworks-spark/shc#259]
Hi all,
I faced with such issue

catalog = ''.join("""{
"table":{"namespace": "mynamespace","name":"table001"},
"rowkey":"id",
"columns":{
    "id":{"cf":"rowkey", "col":"id", "type":"bigint"},
    "pdr_uuid":{"cf":"info", "col":"pdr_uuid", "type":"string"},
    "time":{"cf":"info", "col":"time", "type":"string"},
    "url_params":{"cf":"info", "col":"url_params", "type":"string"},
    "user_agent":{"cf":"info", "col":"user_agent", "type":"string"}
    }
}""".split())

    df.write \
        .options(catalog=catalog, newtable = '5') \
        .format('org.apache.spark.sql.execution.datasources.hbase') \
        .mode("append") \
        .save()

Py4JJavaError: An error occurred while calling o628.save.
: org.apache.hadoop.hbase.regionserver.NoSuchColumnFamilyException: org.apache.hadoop.hbase.regionserver.NoSuchColumnFamilyException: Column family table does not exist in region hbase:meta,,1.1588230740 in table 'hbase:meta', {TABLE_ATTRIBUTES => {IS_META => 'true', REGION_REPLICATION => '1', coprocessor$1 => '|org.apache.hadoop.hbase.coprocessor.MultiRowMutationEndpoint|536870911|'}, {NAME => 'info', BLOOMFILTER => 'NONE', VERSIONS => '3', IN_MEMORY => 'true', KEEP_DELETED_CELLS => 'FALSE', DATA_BLOCK_ENCODING => 'NONE', TTL => 'FOREVER', COMPRESSION => 'NONE', CACHE_DATA_IN_L1 => 'true', MIN_VERSIONS => '0', BLOCKCACHE => 'true', BLOCKSIZE => '8192', REPLICATION_SCOPE => '0'}
	at org.apache.hadoop.hbase.regionserver.HRegion.checkFamily(HRegion.java:8302)

**Comment by GawkVictor** [comment]
Resolved by using version  jar files equal version of HBase

**Comment by deepak1084** [comment]
@GawkVictor Can you please mention the version which you pointed to resolved this bug ? Did you mean the hbase-client-version as 2.0.1 ?

**Comment by shekhfiroz** [comment]
@GawkVictor please help with version jar no

**Comment by omkarahane** [comment]
> Resolved by using version jar files equal version of HBase

@GawkVictor where can I find a mapping of right version of jars (hbase-client, hbase-server) to use vs my version of Hbase. My hbase version is 1.1.2.2.6.3.84-1
