### ISSUE TITLE
How to use avro tablecoder in pyspark for writing dataframe to hbase?

### ISSUE THREAD

**Issue by vineelavelagapudi** [hortonworks-spark/shc#274]
df = spark.read.format("com.databricks.spark.avro").option("schema1",avroSchema).load("path_of_file")

avroSchema = {"namespace": "doctors.avro",
	"type": "record",	"name": "user",
	"fields": [
		
		{"name":"first_name", "type":"string"},
		{"name":"last_name", "type":"string"},
		{"name":"number", "type":"int"}
	]	}

hbaseschema3= {
"table": {"namespace": "default","name": "trip_avro","tableCoder":"avro"},
"rowkey": "key1",
"columns": {
		"col1": {"cf": "rowkey","col": "key1","type": "int"},
		"col2": {"cf": "sales","col": "fields", "avro":"avroSchema"}
		}
}

df.write.option("catalog",hbaseschema3).option("newtable","5").option("avroSchema",avroSchema).format("org.apache.spark.sql.execution.datasources.hbase").save()

Tried with above code but getting error as 'java.lang.ClassNotFoundException: avro
'  by referring https://github.com/hortonworks-spark/shc/wiki/2.-Native-Avro-Support
Can anyone give solution?

**Comment by weiqingy** [comment]
Hi @vineelavelagapudi  
As the step 1 in https://github.com/hortonworks-spark/shc/wiki/2.-Native-Avro-Support shows, when you writing data, you should use `"type":"binary"`.
