### ISSUE TITLE
hbase 0.98 could not be supported for shc ?

### ISSUE THREAD

**Issue by gwdgithubnom** [hortonworks-spark/shc#287]
There is a "no such method" problem about low hbase (0.98 version). Unlucky, we did not know how to select the correct version about shc. Is there anyone given some tips?

**Comment by RumpleZ** [comment]
I had the same problem, the only solution for me was upgrading HBase to 1.1.2 (1.2.6 works too).

**Comment by dongjoon-hyun** [comment]
Sorry guys. We are moving forward.  Spark 2.4 is coming.
