### ISSUE TITLE
1.1.2-2.3-s_2.11-SNAPSHOT shc-core missing from maven

### ISSUE THREAD

**Issue by rsadaphule** [hortonworks-spark/shc#288]
Hi I was using 1.1.2-2.3-s_2.11-SNAPSHOT version of com.hortonworks.shc-core and things were fine until couple of weeks ago. Compilation started failing a week ago and is failing since then. 
I dont see snapshot repo in maven anymore at http://repo.hortonworks.com/content/repositories/snapshots/

Did someone remove it?
Where can I fine latest jar?

If I use latest version from release repo, then connec to to hbase fails. The error is "Failed to load hbase configuration". I am blocked currently and unable to proceed.

**Comment by vivekjain123** [comment]
Hi @rsadaphule you can dowload from http://repo.hortonworks.com/content/repositories/releases/com/hortonworks/shc-core/1.1.1-2.1-s_2.11/. 
This version works fine. In case of issues please read the "readme" carefully.

**Comment by dongjoon-hyun** [comment]
Thank you for Q&A, @rsadaphule and @vivekjain123 .

Actually, we stopped to publish the artifacts. The only official one are the built-in jar file in HDP like the folloinwgs.
```
# ls /usr/hdp/2.6.5.0-292/shc/
shc-core-1.1.0.2.6.5.0-292.jar

# ls /usr/hdp/3.0.1.0-187/shc/
shc-core-1.1.0.3.0.1.0-187.jar
```
