### ISSUE TITLE
Supports Spark 2.4.x?

### ISSUE THREAD

**Issue by jrfineza** [hortonworks-spark/shc#294]
Is there an shc jar that supports spark 2.4.x and up? encountering json4s issue on this version shc-core-1.1.2-2.2-s_2.11-SNAPSHOT, but works on a 2.2 spark cluster.

Thank You

**Comment by dongjoon-hyun** [comment]
Hi, @jrfineza .
If you build from the master branch, it works.

**Comment by moonyouj889** [comment]
> Hi, @jrfineza .
> If you build from the master branch, it works.

Hi, I'm very new to this, and I've been having trouble with the same issue. I'm using pyspark, and I'm not sure what you mean by building from the master branch. Would you mind explaining it a bit more?
