### ISSUE TITLE
Remove deprecation warnings in `branch-2.0` examples

### ISSUE THREAD

**Issue by dongjoon-hyun** [hortonworks-spark/shc#30]
After merging #28 , we had better make examples up-to-date.

**Comment by weiqingy** [comment]
Resolved.

**Comment by dongjoon-hyun** [comment]
You can close issue automatically by adding the following in the commit message. 

> This closes #issueid.

**Comment by weiqingy** [comment]
Thanks for this information. @dongjoon-hyun
