### ISSUE TITLE
Support Travis CI for branch-2.0.0

### ISSUE THREAD

**Issue by dongjoon-hyun** [hortonworks-spark/shc#31]

**Comment by weiqingy** [comment]
Hi, @dongjoon-hyun I have submitted a [commit](https://github.com/hortonworks-spark/shc/commit/c462b028e5befe7352c0b20aa5784501780aa434) for this issue. May I close this issue?

**Comment by dongjoon-hyun** [comment]
Sure! Please close this.

**Comment by weiqingy** [comment]
Thanks, @dongjoon-hyun.
