### ISSUE TITLE
Modify HBaseTableScan to log amount of time to return rows at level info instead of debug

### ISSUE THREAD

**Issue by isaacreath** [hortonworks-spark/shc#41]
At line line 194 in the HBaseTableScan (https://github.com/hortonworks-spark/shc/blob/master/src/main/scala/org/apache/spark/sql/execution/datasources/hbase/HBaseTableScan.scala#L194) the number of rows is logged at the log level debug. By changing the log level to info, users can collect metrics about what percentage of their spark job is time spent taking data out of HBase without having to sort though many of the other debug log messages.

**Comment by Sherry302** [comment]
PR #42 has been merged. Resolved and Close this. Thanks.
