### ISSUE TITLE
How to load a csv into HBaseRecord 

### ISSUE THREAD

**Issue by ashitabh** [hortonworks-spark/shc#47]
Please help with an example of loading a csv into HBaseRecord 
The example provided uses dummy data , but I am looking for something which can help bulk load csv
object HBaseRecord {  def apply(i: Int): HBaseRecord = {    val s = s"""row${"%03d".format(i)}"""
    HBaseRecord(s,      i % 2 == 0,      i.toDouble,      i.toFloat,      i,      i.toLong,      i.toShort,
      s"String$i extra",      i.toByte)  }}

**Comment by weiqingy** [comment]
I am not sure why you want to load a csv into HBaseRecord? Do you mean you want to save your csv file into HBase?

**Comment by ashitabh** [comment]
Hi, 
The use case is to bulk load a CSV to Hbase. Can you help me with an example 
RegardsAshitabh

Sent from Yahoo Mail on Android 
 
  On Mon, Oct 3, 2016 at 7:27 AM, Weiqing Yang<notifications@github.com> wrote:   
I am not sure why you want to load a csv into HBaseRecord? Do you mean you want to save your csv file into HBase?

**Comment by weiqingy** [comment]
CSV has been supported by Spark. So, first, load your csv file to Spark as a DataFrame df. 
e.g. :
```
val session = SparkSession.builder
        .master("local")
        .appName("csv reader")
        .getOrCreate;

val df = session.read
        .format("csv") 
        .option("header", "true") 
        .load("csv/file/path");
```
_Please refer to Spark doc about how to load csv to a Dataframe._

Then save the data to HBase (you also need to defined your HBase catalog "cat", please refer to readme), e.g.
```
df.write.options(
Map(HBaseTableCatalog.tableCatalog->cat,HBaseTableCatalog.newTable->"5"))
.format("org.apache.spark.sql.execution.datasources.hbase")
.save()
```

**Comment by ashitabh** [comment]
Thanks Yang,
I am able to load CSV into hbase using your steps .
Thank you very much

Sent from Yahoo Mail on Android 
 
  On Mon, Oct 3, 2016 at 9:25 AM, Weiqing Yang<notifications@github.com> wrote:   
CSV has been supported by Spark. So, first, load your csv file to Spark as a DataFrame df. 
e.g. :
val session = SparkSession.builder
        .master("local")
        .appName("csv reader")
        .getOrCreate;

val df = session.read
        .format("csv") 
        .option("header", "true") 
        .load("csv/file/path");

Please refer to Spark doc about how to load csv to a Dataframe.

Then save the data to HBase (you also need to defined your HBase catalog "cat", please refer to readme), e.g.
df.write.options(
Map(HBaseTableCatalog.tableCatalog->cat,HBaseTableCatalog.newTable->"5"))
.format("org.apache.spark.sql.execution.datasources.hbase")
.save()

**Comment by weiqingy** [comment]
NP. Resolved. Close this.
