### ISSUE TITLE
support for spark 1.5

### ISSUE THREAD

**Issue by rossrules** [hortonworks-spark/shc#54]
can you add support for 1.5, or is 1.6 backwards compatible to spark 1.5? a package doesn't seem to be available for 1.5.

**Comment by weiqingy** [comment]
Currently [1.5](https://github.com/hortonworks-spark/shc/tree/1.5) works for Spark 1.5. Now the new features are only committed to branch-1.6, branch-2.0 and master. Of course, SHC does welcome PRs to 1.5 branch and before. 

There is no package available in Hortonworks repo, and you need to built it with `mvn package -DskipTests` (please refer the readme doc).

**Comment by barkhorn** [comment]
Any chance you could publish a version build for spark 1.5 to Central?

**Comment by rossrules** [comment]
Nope, sorry i don't have that code base accessible to me anymore.
