### ISSUE TITLE
Reason for numRegion < 3 condition in HBaseRelation

### ISSUE THREAD

**Issue by sachinjain024** [hortonworks-spark/shc#76]
I can see the following code in HBaseRelation.scala

```
if (catalog.numReg > 3) {
      val tName = TableName.valueOf(catalog.name)
      val cfs = catalog.getColumnFamilies

      val connection = HBaseConnectionCache.getConnection(hbaseConf)
      // Initialize hBase table if necessary
      val admin = connection.getAdmin

      // The names of tables which are created by the Examples has prefix "shcExample"
      if (admin.isTableAvailable(tName) && tName.toString.startsWith("shcExample")){
        admin.disableTable(tName)
        admin.deleteTable(tName)
      }

      if (!admin.isTableAvailable(tName)) {
        val tableDesc = new HTableDescriptor(tName)
        cfs.foreach { x =>
         val cf = new HColumnDescriptor(x.getBytes())
          logDebug(s"add family $x to ${catalog.name}")
          tableDesc.addFamily(cf)
        }
        val startKey = Bytes.toBytes("aaaaaaa")
        val endKey = Bytes.toBytes("zzzzzzz")
        val splitKeys = Bytes.split(startKey, endKey, catalog.numReg - 3)
```

I am curious to know the reason for this if condition and I also checked this in HBase shell. By default Hbase creates 3 extra regions. Why so ?

**Comment by weiqingy** [comment]
My memory is that the issues around "3" is related to fit in some requirement of creating region server. Will come back here after figuring out it. @tedyu probably have a better memory of this.

**Comment by sachinjain024** [comment]
@weiqingy I figured out that part later. Here are the calculations:

    Number Of Regions = Number of Splits + 1

Since we have defined two boundaries 'aaaaaa' and 'zzzzzz' that means there will be two regions for keys < 'aaaaaa' and keys > 'zzzzzz'. So the number of splits should be

    NumRegions - 1 - 2
    NumRegions - 3

Closing this ticket.

**Comment by weiqingy** [comment]
Thanks, @sachinjain024

**Comment by adamdec** [comment]
Why start/end keys are defined like aaaaaaa and zzzzzzz?

**Comment by abhiSakhuja** [comment]
@sachinjain024 @weiqingy Sorry but not satisfied with the explanation of minimum number of 3 as follows:

1. HBase initial loads the data into single region and then, do the splitting. However, we have a split range defined based on the number of region, we select (greater than 3 but not sure, why greater than 3).
2. Number of regions = number of splits + 1. How do you define "1"?
3. Given split range has a start and end key of a split within a region and not for two regions.

**Comment by sachinjain024** [comment]
@adamdec I know this is very delayed answer but still answering for future readers. Developer has to provide a beginning and ending key range. When you understand the data that is going into hbase you can better define the boundaries. In this particular example, since we do not know about the boundaries we picked `aaaaa` and `zzzzzz` and we expect the developer to change it according to the data.
