### ISSUE TITLE
Namespace in the catalog is not handled correctly by SHC 

### ISSUE THREAD

**Issue by samouille666** [hortonworks-spark/shc#96]
## Context
I am writing a little tool to move some data from Hive to HBase and I used SHC in this context.
I finished coding the tool (it works nicely !!) and am taking care now of the details.

## Problem
SHC does not seem to take the namespace I give him into account.

## Step to reproduce 
I created a small Hive table:
`case class AgeAndName(age:Int, name:String)`
`val myseq = 1 to 30000 map(x => AgeAndName(x, s"Name$x is a good name "))`
`val myDf = sc.parallelize(myseq).toDF`
`myDf.write.saveAsTable("person.ageAndName")`
(this work provided the DB person exists in Hive).

While processing I am turing the case class to an Avro record and take the age as an id for my Rowkey in HBase (the consistency of the example is not relevant here;)).
 
When inserting the data, I am providing Option as Map[String,String] and inside it the catalog. Here are the logs of YARN that give me info about their content:

`17/02/21 14:00:46 INFO SHCHelper$: Generated catalog: {`
`"table":{"namespace":"person", "name":"ageAndName", "tableCoder":"PrimitiveType"},`
`"rowkey":"age",`
`"columns":{`
`  "age":`
`{"cf":"rowkey", "col":"age", "type":"int"} ,`
`"record":{"cf":"record", "col":"record", "type":"binary"}`
`}`
`}`

And these are the logged option passed to the writer:
`17/02/21 14:00:48 INFO Hive2Hbase$: This options are passed to the writer: namespace -> person,catalog -> {`
`"table":{"namespace":"person", "name":"ageAndName", "tableCoder":"PrimitiveType"},`
`"rowkey":"age",`
`"columns":{`
`  "age":`
`{"cf":"rowkey", "col":"age", "type":"int"} ,`
`"record":{"cf":"record", "col":"record", "type":"binary"}`
`}`
`},newtable -> 5`

The writing works nicely with SHC but when using hbase shell to check the result here I what I can see:
`hbase(main):072:0* list_namespace`
`NAMESPACE`                                                                                                                                             
`default`                                                                                                                                               
`hbase`                                                                                                                                                 
`person`                                                                                                                                                
`3 row(s) in 0.0180 seconds`

`hbase(main):073:0> list_namespace_tables 'person'`
`TABLE                                                                          `                                                                       
`0 row(s) in 0.0110 seconds`

`hbase(main):074:0> list_namespace_tables 'default'`
`TABLE                                                                          `                                                                       
`ageAndName`                                                                                                                                            
`1 row(s) in 0.0110 seconds`

- I tried with already existing namespace in HBase
- I tried with letting shc handling the creation of the namespace (is it suppose to be possible ?)
- I tried without giving him the namespace in the Map[String,String] as option adn letting him find in the catalog.
... but it still is not working.

## Expectation
I expected the namespace person to store the table ageAndName and not the default.
So how does it come that is not the case ?
I am working with this dependency:
`libraryDependencies += "com.hortonworks" % "shc-core" % "1.0.1-1.6-s_2.10"`

**Comment by weiqingy** [comment]
Thanks for proposing this problem. Currently SHC always create a table with "default" namespace. I am going to create a PR to fix this. 
In your code, if you are working with "`1.0.1-1.6-s_2.10`", you do not need to specify "tableCoder":"PrimitiveType", it does not hurt anything though.

**Comment by weiqingy** [comment]
I have submitted a [PR#97](https://github.com/hortonworks-spark/shc/pull/97) for this.

**Comment by samouille666** [comment]
Thanks !
